// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPmLH2fUTDtYfZRXFCckmPqfJPDN66scU',
    appId: '1:971022277239:web:f196ac54c9e1cf477dc472',
    messagingSenderId: '971022277239',
    projectId: 'ucab-c7586',
    authDomain: 'ucab-c7586.firebaseapp.com',
    databaseURL: 'https://ucab-c7586-default-rtdb.firebaseio.com',
    storageBucket: 'ucab-c7586.appspot.com',
    measurementId: 'G-EJWRKS9S06',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-6WOZ68NrvwTTjBTM-LRHPHcVPQ3oui4',
    appId: '1:971022277239:android:7cd1f45003d0f5067dc472',
    messagingSenderId: '971022277239',
    projectId: 'ucab-c7586',
    databaseURL: 'https://ucab-c7586-default-rtdb.firebaseio.com',
    storageBucket: 'ucab-c7586.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR2w8Lu4bm_DWTldVGKyhnCimpEEuVzOw',
    appId: '1:971022277239:ios:cfdd5d6347683a127dc472',
    messagingSenderId: '971022277239',
    projectId: 'ucab-c7586',
    databaseURL: 'https://ucab-c7586-default-rtdb.firebaseio.com',
    storageBucket: 'ucab-c7586.appspot.com',
    iosClientId: '971022277239-9aqirbld3f8hltmlc1vcpdg09itn5gkg.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR2w8Lu4bm_DWTldVGKyhnCimpEEuVzOw',
    appId: '1:971022277239:ios:cfdd5d6347683a127dc472',
    messagingSenderId: '971022277239',
    projectId: 'ucab-c7586',
    databaseURL: 'https://ucab-c7586-default-rtdb.firebaseio.com',
    storageBucket: 'ucab-c7586.appspot.com',
    iosClientId: '971022277239-9aqirbld3f8hltmlc1vcpdg09itn5gkg.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
